services:
  mc:
    container_name: minecraft-server
    hostname: minecraft-server
    image: itzg/minecraft-server
    environment:
      TYPE: "VANILLA"
      EULA: "true"
    ports:
      - "25000:25000"
    volumes:
      - /data/docker_data/minecraft/data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 192.168.0.252


networks:
  net:
    name: docker_public
    external: true
