services:
  mc:
    container_name: ${app_name}
    hostname: ${app_name}
    image: itzg/minecraft-server
    environment:
      TYPE: "VANILLA"
      EULA: "true"
    ports:
      - "25000:25000"
    volumes:
      - data:/data
#      - /data/docker_data/minecraft/data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      net:
        ipv4_address: ${app_ipv4}

volumes:
  data:
    name: minecraft.data

networks:
  net:
    name: docker_public
    external: true
